Final.Web/Controllers/TransferController.cs
using System.Threading.Tasks;
using Azure;
using Final.Services.DTOs.Transfer.Requests;
using Final.Services.DTOs.Transfer.Responses;
using Final.Services.Interfaces.BankAccount;
using Final.Services.Interfaces.Transfer;
using Final.Web.Models;
using Final.Web.Models.BankAccounts;
using Final.Web.Models.Transfer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Office.Web.Attributes;

namespace Final.Web.Controllers
{
    [RequireLogin]
    public class TransferController : Controller
    {
        private readonly IBankAccountService _bankAccountService;
        private readonly ITransferService _transferService;
        public TransferController(IBankAccountService bankAccountService, ITransferService transferService)
        {
            _transferService = transferService;
            _bankAccountService = bankAccountService;
        }
        // GET: TransferController
        public async Task<ActionResult> Index()
        {
            TransferListModel model = new TransferListModel();
            var response = await _transferService.GetTransfersByUser(Convert.ToInt32(HttpContext.Session.GetInt32("UserId")));
            if (response.IsSuccesful)
            {
                foreach (var transfer in response.Transfers)
                {
                    model.Transfers.Add(new TransferModel
                    {
                        TransferId = transfer.TransferId,
                        GoingToNumber = _bankAccountService.GetAccountById(transfer.GoingToId).Result.Account.AccNumber,
                        SenderNumber = _bankAccountService.GetAccountById(transfer.SenderId).Result.Account.AccNumber,
                        TransferAmount = transfer.TransferAmount,
                        TransferReason = transfer.TransferReason,
                        TransferStatus = transfer.TransferStatus,
                        UserId = transfer.UserId
                    });
                }

                return View(model);
            }


            return View("RequestAnswer", new RequestAnswerModel { isSuccess = response.IsSuccesful, message = response.Message });
        }



        // GET: TransferController/Create
        public async Task<IActionResult> Create()
        {
            AccountsListModel model = new AccountsListModel();
            var response = await _bankAccountService.GetAccountsOfUser(Convert.ToInt32(HttpContext.Session.GetInt32("UserId")));
            if (response.IsSuccesful)
            {
                foreach (var acc in response.Accounts)
                {
                    model.Accounts.Add(new AccountModel
                    {
                        AccId = acc.AccId,
                        AccNumber = acc.AccNumber,
                        AccBalance = acc.AccBalance
                    });
                }

                return View(model);
            }


            return View("RequestAnswer", new RequestAnswerModel { isSuccess = response.IsSuccesful, message = response.Message });
        }

        // POST: TransferController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateTransferModel request)
        {
            TransferRequest transferRequest = new TransferRequest
            {
                GoingToAccNumber = request.GoingToAccNumber,
                SenderId = request.SenderId,
                TransferAmount = request.TransferAmount,
                TransferReason = request.TransferReason,
                UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"))

            };

            var response = await _transferService.CreateTransfer(transferRequest);
            return View("RequestAnswer", new RequestAnswerModel { isSuccess = response.IsSuccesful, message = response.Message });
        }

        public async Task<ActionResult> Send(int id)
        {
            AuthRequest request = new AuthRequest
            {
                UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId")),
                TransferId = id
            };
            var response = await _transferService.SendTransfer(request);
            return View("RequestAnswer", new RequestAnswerModel { isSuccess = response.IsSuccesful, message = response.Message });
        }

        public async Task<ActionResult> Cancel(int id)
        {
            AuthRequest request = new AuthRequest
            {
                UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId")),
                TransferId = id
            };
            var response = await _transferService.CancelTransfer(request);
            return View("RequestAnswer", new RequestAnswerModel { isSuccess = response.IsSuccesful, message = response.Message });
        }

        public async Task<ActionResult> Reorder()
        {

            TransferListModel model = new TransferListModel();
            var response = await _transferService.GetTransfersByUser(Convert.ToInt32(HttpContext.Session.GetInt32("UserId")));
            if (response.IsSuccesful)
            {
                foreach (var transfer in response.Transfers)
                {
                    model.Transfers.Add(new TransferModel
                    {
                        TransferId = transfer.TransferId,
                        GoingToNumber = _bankAccountService.GetAccountById(transfer.GoingToId).Result.Account.AccNumber,
                        SenderNumber = _bankAccountService.GetAccountById(transfer.SenderId).Result.Account.AccNumber,
                        TransferAmount = transfer.TransferAmount,
                        TransferReason = transfer.TransferReason,
                        TransferStatus = transfer.TransferStatus,
                        UserId = transfer.UserId
                    });
                }
                model.Transfers = model.Transfers.OrderByDescending(t => t.TransferStatus == "ИЗЧАКВА").ToList();

                return View("Index",model);
            }


            return View("RequestAnswer", new RequestAnswerModel { isSuccess = response.IsSuccesful, message = response.Message });
        }


        public async Task<ActionResult> Incoming() {
            TransferListModel model = new TransferListModel();
            var response = await _transferService.GetTransfersToUser(Convert.ToInt32(HttpContext.Session.GetInt32("UserId")));
            if (response.IsSuccesful)
            {
                foreach (var transfer in response.Transfers)
                {
                    model.Transfers.Add(new TransferModel
                    {
                        TransferId = transfer.TransferId,
                        GoingToNumber = _bankAccountService.GetAccountById(transfer.GoingToId).Result.Account.AccNumber,
                        SenderNumber = _bankAccountService.GetAccountById(transfer.SenderId).Result.Account.AccNumber,
                        TransferAmount = transfer.TransferAmount,
                        TransferReason = transfer.TransferReason,
                        TransferStatus = transfer.TransferStatus,
                        UserId = transfer.UserId
                    });
                }

                return View(model);
            }


            return View("RequestAnswer", new RequestAnswerModel { isSuccess = response.IsSuccesful, message = response.Message });

            
        }
    }
}

Final.Web/Views/Shared/RequestAnswer.cshtml
@model RequestAnswerModel
@{
	ViewData["Title"] = "Request Status";
}

<h1>Request Status</h1>
@if (Model.isSuccess)

{
	<h2 class="text-success">Request was successful!</h2>
	;
}
else{
	<h2>@Model.message</h2>
}

Final.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Final.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Final.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Final.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transfer" asp-action="Create">New Transfer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transfer" asp-action="Index">My Transfers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transfer" asp-action="Incoming">Incoming Transfers</a>
                        </li>
                    </ul>

                    
                    <form class="d-flex ms-auto" asp-area="" asp-controller="LogIn" asp-action="Logout" method="post">
                        <button type="submit" class="btn btn-outline-danger">Logout</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Final.Web 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>